# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  - master

stages:
- stage: Install
  displayName: 'Install dependencies and run tests'

  jobs:
  - job: Install
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-16.04'
        mac:
          imageName: 'macos-10.13'
        windows:
          imageName: 'vs2017-win2016'

    pool:
      vmImage: $(imageName)
    displayName: "Install Dependencies and Run Tests"

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: "10.x"
      displayName: "Use Node.js 10"

    - script: yarn --no-progress --frozen-lockfile
      workingDirectory: "./demo-app"
      displayName: "Install dependencies"

    - script: yarn test
      workingDirectory: "./demo-app"
      displayName: "Run tests"

    - script: yarn run build
      workingDirectory: "./demo-app"
      displayName: "Build Gatsby App"